apiVersion: v1
kind: Service
metadata:
  name: portainer-service
spec:
  selector:
    name: portainer
  type: NodePort
  ports:
  - port: 80
    targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-service
spec:
  selector:
    name: rancher
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
