apiVersion: v1
kind: Service
metadata:
  name: blue-service
spec:
  selector:
    app: blue
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: purple-service
spec:
  selector:
    app: purple
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
