apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: host-based-ingress
spec:
  rules:
  - host: blue.demo.com 
    http:
      paths:
      - backend:
          serviceName: blue-service
          servicePort: 80
  - host: purple.demo.com
    http:
      paths:
      - backend:
          serviceName: purple-service
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: path-based-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /blue
        backend:
          serviceName: blue-service
          servicePort: 80
      - path: /purple
        backend:
          serviceName: purple-service
          servicePort: 80
